version: 2
updates:
  - package-ecosystem: 'pnpm'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5
    groups:
      github-actions:
        patterns:
          - '*'
