name: tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      APP_LOCALE: zh_TW

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: composer:v2

      - name: Setup pnpm
        uses: pnpm/setup@v1
        with:
          version: 12
          runtime: node@26
          cache: true

      - name: Setup Application
        run: composer setup

      - name: Run CI Checks
        run: composer ci:check
